version: '2'

services:
  shadowsocks-docker:
    image: registry.cn-hangzhou.aliyuncs.com/lancger_ops/shadowsocks-docker:v1.0.0
    restart: always
    ports:
      - "8388:8388"
    environment:
      SS_SERVER_ADDR: 0.0.0.0
      SS_SERVER_PORT: 8388
      SS_PASSWORD: password
      SS_METHOD: aes-256-cfb
      SS_TIMEOUT: 300
